# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3709a190633a703ff6f4e0476cf5a65fb367f73ac6b71b2f9b51be1dc52eea7848d9d2735c9434123797f63d45a8f7f069eeb721f9ce5cdd7e34d7077a8a3721

test:
  secret_key_base: 1f524f63e77ddede45ee745ef9ed60369744841faf23411880878597566d5688e276e600eeb922fe7a8843f6e9887ec5315ade4bf9e3c633791f66179a9353bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
